"use client";

import React from 'react';
import { ModernNav } from '@/components/shared/ModernNav';
import { Footer } from '@/components/shared/Footer';

export default function TermsPage() {
    return (
        <div className="bg-background-primary min-h-screen text-text-primary">
            <ModernNav />
            <main className="container mx-auto px-6 py-32 max-w-4xl">
                <h1 className="text-4xl font-bold mb-8 text-white">Terms of Service</h1>
                <p className="text-text-secondary mb-6 italic">Last updated: March 06, 2026</p>

                <section className="space-y-8 prose prose-invert max-w-none text-text-secondary">
                    <div>
                        <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
                        <p>
                            By accesssing or using ContextMatic, you agree to be bound by these Terms of Service. If you do not agree, please do not use our services.
                        </p>
                    </div>

                    <div>
                        <h2 className="text-2xl font-semibold text-white mb-4">2. AI Content Generation</h2>
                        <p>
                            ContextMatic provides AI-powered tools for content creation. While we strive for accuracy, we cannot guarantee the quality or correctness of the output generated by third-party AI models (Gemini, OpenAI, etc.). Users are responsible for reviewing all generated content.
                        </p>
                    </div>

                    <div>
                        <h2 className="text-2xl font-semibold text-white mb-4">3. Subscriptions & Credits</h2>
                        <p>
                            Certain features require a paid subscription or credits. Credits are non-refundable and expire based on your plan terms. We reserve the right to modify pricing with 30 days notice.
                        </p>
                    </div>

                    <div>
                        <h2 className="text-2xl font-semibold text-white mb-4">4. Prohibited Use</h2>
                        <p>
                            You agree not to use ContextMatic for generating illegal, harmful, or deceptive content, or for infringing on any third-party intellectual property rights.
                        </p>
                    </div>
                </section>
            </main>
            <Footer />
        </div>
    );
}
