import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import ContentCreator from './ContentCreator';

const Dashboard: React.FC = () => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const [generatedContent, setGeneratedContent] = useState<string | null>(null);
  const [contentFormat, setContentFormat] = useState<string>('');

  const handleGenerate = (content: string, format: string) => {
    // Simulate AI content generation
    const formatLabels: Record<string, string> = {
      summary: 'Concise Summary',
      tweet_thread: 'Twitter Thread',
      blog_post: 'Blog Post',
      linkedin_post: 'LinkedIn Post',
      email_newsletter: 'Email Newsletter'
    };

    const generated = `🎯 ${formatLabels[format]}\n\n${content.substring(0, 200)}...\n\n✨ Generated by ContextMatics AI`;
    setGeneratedContent(generated);
    setContentFormat(format);
  };

  if (!user) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 flex items-center justify-center">
        <div className="bg-white/10 backdrop-blur-md rounded-2xl p-8 border border-white/20 text-center">
          <h2 className="text-2xl font-bold text-white mb-4">Please Log In</h2>
          <p className="text-white/70 mb-6">You need to be logged in to access the dashboard.</p>
          <button
            onClick={() => navigate('/')}
            className="bg-gradient-to-r from-purple-500 to-pink-500 text-white px-6 py-3 rounded-xl font-semibold hover:from-purple-600 hover:to-pink-600 transition-all"
          >
            Go to Home
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 py-8">
      {/* Navigation */}
      <nav className="bg-black/20 backdrop-blur-md border-b border-white/10 mb-8">
        <div className="max-w-7xl mx-auto px-8 py-4">
          <div className="flex justify-between items-center">
            <button
              onClick={() => navigate('/')}
              className="text-2xl font-bold bg-gradient-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent"
            >
              ContextMatics
            </button>
            <div className="flex items-center space-x-6">
              <button
                onClick={() => navigate('/pricing')}
                className="text-white/80 hover:text-white transition-colors"
              >
                Pricing
              </button>
              <button
                onClick={() => navigate('/subscription')}
                className="text-white/80 hover:text-white transition-colors"
              >
                Subscription
              </button>
              <button
                onClick={logout}
                className="bg-red-500/20 border border-red-400/30 text-red-300 px-4 py-2 rounded-lg hover:bg-red-500/30 transition-all"
              >
                Logout
              </button>
            </div>
          </div>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Stats Cards */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          <div className="bg-gradient-to-br from-blue-500/20 to-cyan-500/20 backdrop-blur-md rounded-2xl p-6 border border-white/20">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-semibold text-white/80 mb-2">Credits Remaining</h3>
                <p className="text-4xl font-bold text-white">{user.processingCredits}</p>
              </div>
              <div className="text-5xl">💎</div>
            </div>
          </div>

          <div className="bg-gradient-to-br from-green-500/20 to-emerald-500/20 backdrop-blur-md rounded-2xl p-6 border border-white/20">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-semibold text-white/80 mb-2">Current Plan</h3>
                <p className="text-4xl font-bold text-white capitalize">{user.plan}</p>
              </div>
              <div className="text-5xl">🚀</div>
            </div>
          </div>

          <div className="bg-gradient-to-br from-purple-500/20 to-pink-500/20 backdrop-blur-md rounded-2xl p-6 border border-white/20">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-semibold text-white/80 mb-2">Account Status</h3>
                <p className="text-4xl font-bold text-white">Active</p>
              </div>
              <div className="text-5xl">✨</div>
            </div>
          </div>
        </div>

        {/* Content Creator */}
        <div className="grid md:grid-cols-2 gap-8">
          <ContentCreator onGenerate={handleGenerate} />

          {/* Output Area */}
          <div className="bg-white/10 backdrop-blur-md rounded-2xl p-8 border border-white/20">
            <h2 className="text-3xl font-bold text-white mb-6">Generated Content</h2>
            
            {generatedContent ? (
              <div className="space-y-4">
                <div className="bg-white/5 border border-white/20 rounded-xl p-6">
                  <div className="flex items-center justify-between mb-4">
                    <span className="text-purple-400 font-semibold">Format: {contentFormat}</span>
                    <button
                      onClick={() => navigator.clipboard.writeText(generatedContent)}
                      className="bg-purple-500/20 border border-purple-400/30 text-purple-300 px-4 py-2 rounded-lg hover:bg-purple-500/30 transition-all text-sm"
                    >
                      📋 Copy
                    </button>
                  </div>
                  <pre className="text-white/90 whitespace-pre-wrap font-mono text-sm leading-relaxed">
                    {generatedContent}
                  </pre>
                </div>
                
                <div className="flex gap-4">
                  <button className="flex-1 bg-gradient-to-r from-green-500 to-emerald-500 text-white px-6 py-3 rounded-xl font-semibold hover:from-green-600 hover:to-emerald-600 transition-all">
                    💾 Save
                  </button>
                  <button className="flex-1 bg-gradient-to-r from-blue-500 to-cyan-500 text-white px-6 py-3 rounded-xl font-semibold hover:from-blue-600 hover:to-cyan-600 transition-all">
                    📤 Export
                  </button>
                </div>
              </div>
            ) : (
              <div className="h-full flex items-center justify-center text-center">
                <div>
                  <div className="text-6xl mb-4">🎨</div>
                  <p className="text-white/60 text-lg">
                    Your generated content will appear here
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Recent Activity */}
        <div className="mt-8 bg-white/10 backdrop-blur-md rounded-2xl p-8 border border-white/20">
          <h2 className="text-2xl font-bold text-white mb-6">Recent Activity</h2>
          <div className="space-y-4">
            <div className="bg-white/5 border border-white/10 rounded-xl p-4 flex items-center justify-between">
              <div className="flex items-center space-x-4">
                <div className="w-12 h-12 bg-purple-500/20 rounded-full flex items-center justify-center text-2xl">
                  📝
                </div>
                <div>
                  <p className="text-white font-semibold">Blog Post Generated</p>
                  <p className="text-white/60 text-sm">2 hours ago</p>
                </div>
              </div>
              <span className="text-green-400 font-semibold">Success</span>
            </div>
            
            <div className="bg-white/5 border border-white/10 rounded-xl p-4 flex items-center justify-between">
              <div className="flex items-center space-x-4">
                <div className="w-12 h-12 bg-blue-500/20 rounded-full flex items-center justify-center text-2xl">
                  🐦
                </div>
                <div>
                  <p className="text-white font-semibold">Twitter Thread Created</p>
                  <p className="text-white/60 text-sm">5 hours ago</p>
                </div>
              </div>
              <span className="text-green-400 font-semibold">Success</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;